### ISSUE TITLE
Steepfall Burrow Revisited install screen

### ISSUE THREAD

**Issue by RandySaint** [ErikJohnsson/DungeonsRevisited#20]
The Steepfall Burrow Revisited install screen in Vortex shows that the file being loaded is EmbershardMineRevisited.esp

![image](https://user-images.githubusercontent.com/25558946/90205638-52b41800-dda8-11ea-8748-28780206d18e.png)

It appears to have actually installed SteepfallBurrowRevisited.esp
So perhaps it's just the display label in the install script.

**Comment by ErikJohnsson** [comment]
This is just a visual bug but should be fixed, thank you.

**Comment by ErikJohnsson** [comment]
Fixed in 1.1 of steepfall burrow
