### ISSUE TITLE
Suggested Location: Broken Helm Hollow

### ISSUE THREAD

**Issue by dap1984** [ErikJohnsson/DungeonsRevisited#25]
I feel like this place has a lot of potential, it already has a "secret" door that leads to well....nowhere really. I wasn't sure where to put suggestions, I find the github UI counter-intuitive, sorry! https://elderscrolls.fandom.com/wiki/Broken_Helm_Hollow_(Skyrim)

**Comment by ErikJohnsson** [comment]
Thank you for the suggestion! I will eventually get to this dungeon but right now im focusing on all the dungeons in whiterun hold. Closing this for now.
