### ISSUE TITLE
Ustengrav enchanting table bug

### ISSUE THREAD

**Issue by BrotherErryn** [ErikJohnsson/DungeonsRevisited#26]
There is a room in Ustengrav Depths, with two hanging pots, two "occupied" crypts, and two twisting handles to open two gates to reach a chest and an enchanting table. That enchanting table doesn't seem to work. You can activate it, get the normal animation, and the menu comes up...but there is no mouse cursor and no keys work except to TAB out of it. Other enchanting tables work as expected. I feel like I've seen this happen in other mods before, but I don't remember specifically.

**Comment by ErikJohnsson** [comment]
Can't reproduce.
