### ISSUE TITLE
Ustengrav - Void on door

### ISSUE THREAD

**Issue by cethien** [ErikJohnsson/DungeonsRevisited#34]
![ScreenShot5](https://user-images.githubusercontent.com/60463918/104942124-529df100-59b4-11eb-8652-e2999372e5fb.png)
- can't tell which room, therefor the coordinates.
- when going through the void, it vanishes.
- no ENB, only ELFX and Vivid Weathers for lighting

**Comment by ErikJohnsson** [comment]
Cant reproduce. Closing.
