### ISSUE TITLE
Bleak Falls Barrow: misplaced (?) mesh

### ISSUE THREAD

**Issue by cethien** [ErikJohnsson/DungeonsRevisited#35]
![ScreenShot7](https://user-images.githubusercontent.com/60463918/105219868-3dad9300-5b57-11eb-9550-686b0966fb33.png)
dunno how to call it, in the first segment of bleak falls barrow is a bad placed mash. see screenshot

**Comment by ErikJohnsson** [comment]
My mod does not edit that area,  must be something else causing it.
