### ISSUE TITLE
void rooms in bleak falls temple

### ISSUE THREAD

**Issue by NIMZ203** [ErikJohnsson/DungeonsRevisited#36]
i'm using ELFX and ENB 
i tired putting bleak falls barrow revisited under elfx and above the patches it still didn't work. 
![barrow](https://user-images.githubusercontent.com/80907452/111648009-44791f00-8803-11eb-8168-6ce6a3aa6a3c.png)
![SkyrimSE 2021-03-18 15-53-44](https://user-images.githubusercontent.com/80907452/111648074-51960e00-8803-11eb-8bd4-74f9c2aeaae2.png)
![SkyrimSE 2021-03-18 15-53-50](https://user-images.githubusercontent.com/80907452/111648524-bcdfe000-8803-11eb-9e7a-76136702e7a3.png)

**Comment by ErikJohnsson** [comment]
Some sort of compatibility issue. Report back if you find what is causing the issue.
