### ISSUE TITLE
Invisible Cells Bleak Falls

### ISSUE THREAD

**Issue by BlueKyanight** [ErikJohnsson/DungeonsRevisited#39]
![The Elder Scrolls V  Skyrim Special Edition Screenshot 2021 07 03 - 20 18 59 81](https://user-images.githubusercontent.com/86879210/124354013-6ffe0900-dc3c-11eb-81df-d687f3841826.png)
![The Elder Scrolls V  Skyrim Special Edition Screenshot 2021 07 03 - 20 18 40 74](https://user-images.githubusercontent.com/86879210/124354015-72f8f980-dc3c-11eb-99bd-b68c778b5ef3.png)
![The Elder Scrolls V  Skyrim Special Edition Screenshot 2021 07 03 - 20 18 49 15](https://user-images.githubusercontent.com/86879210/124354017-75f3ea00-dc3c-11eb-8d48-2957df8b9c32.png)

**Comment by ChipsMuhNips** [comment]
I have the same issue.
![489830_20210705150750_1](https://user-images.githubusercontent.com/86984797/124514914-bfab1480-dda3-11eb-9320-cb5435af7b2a.png)
![489830_20210705150812_1](https://user-images.githubusercontent.com/86984797/124514915-c0dc4180-dda3-11eb-9ba8-e32a274ac564.png)

**Comment by JiNama** [comment]
Same issue here. Glad I found the culprit at least.
![image](https://user-images.githubusercontent.com/37218166/125148115-51998100-e106-11eb-8eac-e90988574d2c.png)
![image](https://user-images.githubusercontent.com/37218166/125148116-53fbdb00-e106-11eb-8dac-85c2f7662137.png)

**Comment by ErikJohnsson** [comment]
This is a compatibility issue, probably with a lighting mod.

**Comment by ErikJohnsson** [comment]
Would be nice if you could list your mods and load order.

**Comment by ChipsMuhNips** [comment]
Actually I discovered through its forum comments that this issue is
resolved by moving the mod to the bottom of your load order.
