### ISSUE TITLE
Weird texture bug multiple floor levels..

### ISSUE THREAD

**Issue by JiriHodan** [ErikJohnsson/DungeonsRevisited#46]
Hi I see thro walls or levels when u see enemies far in a  distance and when u reach the cave point where u see blue textures bug it changes to visible but in the other distance same bug..
Is it your mod?
thx,
Jiri

https://github.com/ErikJohnsson/DungeonsRevisited/issues

**Comment by ErikJohnsson** [comment]
Seems like a compatibility issue with another mod. Probably a lighting mod. Closing.
