### ISSUE TITLE
Duplicate rooms/doors layered on top of each other and CTD in Bleak Falls Barrow

### ISSUE THREAD

**Issue by flubing** [ErikJohnsson/DungeonsRevisited#47]
first time going through BFB with this mod and I'm enjoying all the new twists and turns, that is until I went to pick an expert lock and once I was finished the door swung open to reveal another expert level door, I thought to myself "okay, this must a pretty good room to have two doors like this." but I end up clearing it easily without too much loot and go to exit through the other set of doors which again are duplicated, I didn't really think much of it after that but then I started to notice identical bodies stacked on top each other.

I finished the simple stone puzzle door, go through the gate and go right, more duplicate doors, after that I turned around to go down the spiral staircase and end up crashing as I get to the opening, I've also experienced another CTD around the start of the dungeon where the bandit sleeping quarters are .

**Comment by darkangel2041** [comment]
Currently same problem. I CTD juste bfor the down spiral stair case. I have double door too. I checked my mod list if I didn't have "dublicate data" somewhere. Till now, I didn't find anything. Currently what is strange, is that I am not able to find the goldclaw with console command.

**Comment by darkangel2041** [comment]
Finaly solved this problem... it is not from the mod. I also have a mod called "Black Falls Barrow revisited" activated. Removing that mod solved double doors and CTD.

**Comment by ErikJohnsson** [comment]
Yeah you can't use both the individual mods and the all-in-one mod at the same time. Closing.
