### ISSUE TITLE
Still getting floating candles with ELFX

### ISSUE THREAD

**Issue by SkywardStar2000** [ErikJohnsson/DungeonsRevisited#49]
After loading Dungeons - Revisited over ELFX I still have floating candles at least in Bleakfall Barrow. I haven't gone in any other dungons yet

![20220201232922_1](https://user-images.githubusercontent.com/98865966/152094005-653bd2a2-408b-436f-b2c0-4dcd7997d01e.jpg)
![20220201233235_1](https://user-images.githubusercontent.com/98865966/152094017-3ebdbe66-3a02-4236-a0ad-3f7975ed44b1.jpg)
.

**Comment by Litlesmall** [comment]
I'm getting same thing. And I already checked load order.

**Comment by ErikJohnsson** [comment]
Can't find. Must be a problem with the patch.
