### ISSUE TITLE
Texture bug when used with "Draugr Upgrades and Improvements"

### ISSUE THREAD

**Issue by tz-dev** [ErikJohnsson/DungeonsRevisited#50]
Draugr Upgrades and Improvements (Draugr and Skeleton Overhaul) - Update v2.4.2
https://www.nexusmods.com/skyrimspecialedition/mods/21775

Only parts of the Draugr guardians are visible, e.g. Torso is missing.

**Comment by ErikJohnsson** [comment]
Don't see how my mod could conflict with that mod. Closing.
