### ISSUE TITLE
can see through the new areas of bleakfalls barrow

### ISSUE THREAD

**Issue by PrinceJaxonHellsing** [ErikJohnsson/DungeonsRevisited#51]
So when I went to bleakfalls barrow and went farther in, the new areas I can see through and if I adjust my camera it shows again but it's very annoying and I can't see where I'm going half the time. (I'm not sure if it's cause my dyndolod is messed up or the mod itself)

**Comment by ByucknahTheRed** [comment]
Yep, same issue here.

**Comment by ByucknahTheRed** [comment]
OH! I fixed it for myself. Are you using ELFX? If so, move it to load after all the ELFX plugins. I wasn't using ELFX Hardcore but I was using the mod and moving the dungeon mod to load after ELFX fixed it for me.

**Comment by gdarthy** [comment]
I have this issue even when I don't use ELFX mod. However, I have Lux mod (Lux orbis and Lux Via too), but I noticed this Dungeons revisited mod works (the see through areas are gone) if I load it after Lux mods - but I use ENB series mods and the lighting has no effect in new areas - so if I dimmer them the original areas are too dark to see anything.

**Comment by ErikJohnsson** [comment]
Compatibility issue, closing.
