### ISSUE TITLE
Floating stone pillar in White River Watch

### ISSUE THREAD

**Issue by Zerahar** [ErikJohnsson/DungeonsRevisited#52]
![20220410122216_1](https://user-images.githubusercontent.com/26765371/162611647-bd9e5570-6a90-4c56-a2ac-8dad6a97fdf7.jpg)
![Inked20220410122610_1_LI](https://user-images.githubusercontent.com/26765371/162611702-8470f265-854c-463d-b346-be25d517e38d.jpg)

**Comment by ErikJohnsson** [comment]
Not present in my game or in the creation kit. Compatibility issue? But seems unlikely. Dont know what is causing this.
